name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          source .github/CI/spack_setup.sh
          sload gcc@7.3.0%gcc@4.8.5
          spack compiler find
          spack unload -a
          cp .github/CI/spack.yaml .
          spack env activate -d .
          spack install

      - name: Build
        run: |
          source .github/CI/spack_setup.sh
          mkdir build && cd build
          spack env activate -d ..
          spack load --first gcc cmake fftw heffte openmpi
          HEFFTE=`spack location -i heffte`
          FFTW=`spack location -i fftw`
          MPI_DIR=`spack location -i openmpi`
          
          cmake -DFIBER_ENABLE_HEFFTE=ON -DFIBER_ENABLE_FFTW=ON \
             -DFIBER_FFT_INCLUDE_DIRS=$HEFFTE/include;$FFTW/include \
             -DFIBER_FFT_LIB_DIRS=$HEFFTE/lib;$FFTW/lib \  
             -DMPI_DIR=$MPI_DIR ..
          make VERBOSE=1
          
          cd benchmarks
          ls -l
          mpirun -n 2 ./test3D_CPU_C2C heffte
          mpirun -n 2 ./test3D_CPU_R2C heffte
          mpirun -n 2 ./test3D_CPU_C2C fftw
          mpirun -n 2 ./test3D_CPU_R2C fftw
          echo Done
