# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          source ~/spack_setup
          spack install cmake
          spack install fftw
          spack install heffte+fftw

      - name: Build
        run: |
          mkdir build && cd build
          source ~/spack_setup
          spack load --first cmake fftw heffte
          HASH=`spack find --no-groups --loaded -l heffte | awk '{print $1}'`
          HEFFTE=`spack location -i /$HASH`
          cmake -DFIBER_ENABLE_HEFFTE=ON -DFIBER_FFT_INCLUDE_DIRS=$HEFFTE/include -DFIBER_FFT_LIB_DIRS=$HEFFTE/lib ..
          make VERBOSE=1
